disabled_rules:
- line_length
- trailing_whitespace
- orphaned_doc_comment
- nesting
- todo

included:
excluded:
- Pods
- Earth1round-iOS/Global/Support/AppDelegate.swift
- Earth1round-iOS/Global/Support/SceneDelegate.swift

identifier_name:
  excluded:
    - id
